### ISSUE TITLE
Is closing untitled/unsaved

### ISSUE THREAD

**Issue by Noitidart** [Gruntfuggly/closeunmodified#5]
This tries to close untitled/unsaved documents, which causes a prompt to show "would you like to save". Please make it skip "unittled/unsaved" tabs.

**Comment by Gruntfuggly** [comment]
Will look into it.

**Comment by Noitidart** [comment]
Thank you sir!!

**Comment by Gruntfuggly** [comment]
Hmm - I've had a play and I can't reproduce the problem. It checks the 'dirty' flag and ignores any editors which are dirty, but it doesn't do anything else special.
Can you give me some more context? If you could post your settings, that would be useful too. Also, what platform are you using?

**Comment by Noitidart** [comment]
Darn. Thanks very much sir for giving it shot and continuing to give it a shot by asking me for more info. I am on Windows 10. I will take a screencast recording and upload for you :)

By settings would you like me to copy paste what shows up in `Ctrl + ,` ?

**Comment by Gruntfuggly** [comment]
Yes that would be useful - there maybe something that make it behave differently to my set up.
